# Generated by Django 4.2.3 on 2023-07-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thesaurus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("link", models.CharField(max_length=200)),
                ("deprecated", models.BooleanField(default=False)),
                ("searched_for_datasets", models.BooleanField(default=False)),
                (
                    "parent_thesaurus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thesaurus.thesaurus",
                    ),
                ),
                (
                    "related_thesauri",
                    models.ManyToManyField(blank=True, to="thesaurus.thesaurus"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                (
                    "thesaurus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="thesaurus.thesaurus",
                    ),
                ),
            ],
            options={
                "unique_together": {("language", "name")},
            },
        ),
    ]
