# Generated by Django 4.2.3 on 2023-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesaurus",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
