# Generated by Django 4.2.3 on 2023-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translations",
            name="language",
            field=models.CharField(max_length=2),
        ),
    ]
