# Generated by Django 4.2.3 on 2023-07-05 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0002_alter_thesaurus_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thesaurus",
            old_name="url",
            new_name="link",
        ),
    ]
