# Generated by Django 4.2.3 on 2023-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0003_rename_url_thesaurus_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesaurus",
            name="related_thesauri",
            field=models.ManyToManyField(blank=True, to="thesaurus.thesaurus"),
        ),
    ]
