connectors = [
    "and",
    "or",
    "but",
    "while",
    "although",
    "though",
    "even though",
    "if",
    "unless",
    "until",
    "since",
    "because",
    "so that",
    "in order to",
    "while",
    "whereas",
    "after",
    "before",
    "when",
    "whenever",
    "whether",
    "either",
    "neither",
    "nor",
    "not only",
    "but also",
    "as well as",
    "just as",
    "even if",
    "once",
    "provided that",
    "as long as",
    "wherever",
    "however",
    "otherwise",
    "besides",
    "furthermore",
    "meanwhile",
    "therefore",
    "thus",
    "hence",
    "consequently",
    "accordingly",
    "otherwise",
    "meanwhile",
    "nevertheless",
    "nonetheless",
    "however",
    "on the other hand",
    "in contrast",
    "otherwise",
    "rather",
    "instead",
    "yet",
    "still",
]