# Generated by Django 4.2.3 on 2023-08-27 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="documents",
            table="documents",
        ),
    ]
