# Generated by Django 4.2.3 on 2023-08-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0010_alter_translations_unique_together_and_more"),
        ("documents", "0002_alter_documents_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="categories",
            field=models.ManyToManyField(to="categories.categories"),
        ),
    ]
