# Generated by Django 4.2.3 on 2023-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_documents_img_alter_documents_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="authors",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
