# Generated by Django 4.2.3 on 2023-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_alter_documents_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="num_of_access",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
