# Generated by Django 4.2.3 on 2023-08-27 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("categories", "0001_initial"),
        ("categories", "0002_rename_parent_categorie_categories_parent_category"),
        ("categories", "0003_authorities"),
        ("categories", "0004_categories_authority"),
        ("categories", "0005_categories_label_index"),
        ("categories", "0006_authorities_active_authorities_color_and_more"),
        ("categories", "0007_alter_authorities_color"),
        ("categories", "0008_alter_authorities_color"),
        ("categories", "0009_authorities_theoretical_precision_and_more"),
        ("categories", "0010_alter_translations_unique_together_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authorities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("last_training_date", models.DateField(blank=True, null=True)),
                ("native", models.BooleanField(default=False)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_TRAINED", "Not Trained"),
                            ("TRAINING", "Training"),
                            ("COMPLETE", "Complete"),
                            ("GETTING_DATA", "Getting Data"),
                        ],
                        default="NOT_TRAINED",
                        max_length=20,
                    ),
                ),
                (
                    "theoretical_precision",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("link", models.CharField(max_length=200)),
                ("deprecated", models.BooleanField(default=False)),
                ("searched_for_datasets", models.BooleanField(default=False)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.categories",
                    ),
                ),
                (
                    "related_categories",
                    models.ManyToManyField(blank=True, to="categories.categories"),
                ),
                (
                    "authority",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.authorities",
                    ),
                ),
                ("label_index", models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=200)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="categories.categories",
                    ),
                ),
            ],
            options={
                "unique_together": set(),
            },
        ),
        migrations.AlterModelTable(
            name="authorities",
            table="categories_authorities",
        ),
        migrations.AlterModelTable(
            name="categories",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="translations",
            table="categories_translations",
        ),
    ]
