# Generated by Django 4.2.3 on 2023-08-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authorities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("color", models.CharField(blank=True, max_length=7)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "theoretical_precision",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_TRAINED", "Not Trained"),
                            ("TRAINING", "Training"),
                            ("COMPLETE", "Complete"),
                            ("GETTING_DATA", "Getting Data"),
                        ],
                        default="NOT_TRAINED",
                        max_length=20,
                    ),
                ),
                ("last_training_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("native", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "categories_authorities",
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("link", models.CharField(max_length=200)),
                ("label_index", models.BigIntegerField(null=True)),
                ("deprecated", models.BooleanField(default=False)),
                ("searched_for_datasets", models.BooleanField(default=False)),
                (
                    "authority",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.authorities",
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.categories",
                    ),
                ),
                (
                    "related_categories",
                    models.ManyToManyField(blank=True, to="categories.categories"),
                ),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=200)),
                (
                    "categories",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="categories.categories",
                    ),
                ),
            ],
            options={
                "db_table": "categories_translations",
            },
        ),
    ]
