# Generated by Django 4.2.3 on 2023-07-23 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="parent_categorie",
            new_name="parent_category",
        ),
    ]
