# Generated by Django 4.2.3 on 2023-08-28 13:48

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="parent_category",
        ),
        migrations.AddField(
            model_name="categories",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categories",
            name="lft",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categories",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="categories.categories",
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="rght",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="categories",
            name="tree_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="translations",
            unique_together={("language", "name")},
        ),
    ]
