# Generated by Django 4.2.3 on 2023-08-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "categories",
            "0002_remove_categories_parent_category_categories_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="authorities",
            name="pid",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
