# Generated by Django 4.2.3 on 2023-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_rename_parent_categorie_categories_parent_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
