# Generated by Django 4.2.3 on 2023-08-30 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_authorities_pid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translations",
            old_name="categories",
            new_name="category",
        ),
    ]
