# Generated by Django 4.2.3 on 2023-07-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_authorities"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="authority",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.authorities",
            ),
        ),
    ]
