# Generated by Django 4.2.3 on 2023-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_categories_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="label_index",
            field=models.BigIntegerField(null=True),
        ),
    ]
