# Generated by Django 4.2.3 on 2023-09-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0004_rename_categories_translations_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
