# Generated by Django 4.2.3 on 2023-09-08 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0005_alter_categories_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translations",
            unique_together={("language", "name", "category")},
        ),
    ]
