# Generated by Django 4.2.3 on 2023-08-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_alter_authorities_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorities",
            name="theoretical_precision",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="authorities",
            name="color",
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
