# Generated by Django 4.2.3 on 2023-08-27 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0009_authorities_theoretical_precision_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translations",
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name="authorities",
            table="categories_authorities",
        ),
        migrations.AlterModelTable(
            name="categories",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="translations",
            table="categories_translations",
        ),
    ]
