# Generated by Django 4.2.3 on 2023-09-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0010_authorities_disabled_alter_authorities_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorities",
            name="accuracy",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="authorities",
            name="num_documents_classified",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
