# Generated by Django 4.2.3 on 2023-09-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0011_authorities_accuracy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="level",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categories",
            name="lft",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categories",
            name="rght",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categories",
            name="tree_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
