# Generated by Django 4.2.3 on 2023-09-21 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0012_alter_categories_level_alter_categories_lft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="tree_id",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(9999999999)],
            ),
        ),
    ]
