# Generated by Django 4.2.3 on 2023-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0013_alter_categories_tree_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorities",
            name="accuracy",
        ),
        migrations.AddField(
            model_name="authorities",
            name="practical_precision",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
