# Generated by Django 4.2.3 on 2023-09-21 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0015_alter_categories_tree_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="tree_id",
            field=models.PositiveBigIntegerField(
                default=0,
                max_length=999999999,
                validators=[django.core.validators.MaxValueValidator(99999999)],
            ),
        ),
    ]
