# Generated by Django 4.2.3 on 2023-09-22 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0016_alter_categories_tree_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorities",
            name="autoSync",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="categories",
            name="tree_id",
            field=models.PositiveBigIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(99999999)],
            ),
        ),
    ]
